services:
    mashtoo:
        build:
            context: .
            args:
                ARCH: ${ARCH:-amd64}
                MICROARCH: ${MICROARCH:-}
                DIST: ${DIST:-debian}
                VERSION: ${VERSION:-latest}
                NETINST: ${NETINST:-0}
                SYSINIT: ${SYSINIT:-systemd}
                LOG_LEVEL: ${LOG_LEVEL:-ALL}

        container_name: mashtoo
        environment:
            - ARCH=${ARCH:-amd64}
            - MICROARCH=${MICROARCH:-}
            - DIST=${DIST:-debian}
            - VERSION=${VERSION:-latest}
            - NETINST=${NETINST:-0}
            - SYSINIT=${SYSINIT:-systemd}
            - LOG_LEVEL=${LOG_LEVEL:-ALL}
#            - SUFFIX=${SUFFIX}
#            - USB_DEVICE=${USB_DEVICE}
#        privileged: true
#        devices:
#            - /dev:/dev
        volumes:
            - ./:/home/mashtoo

#networks:
#    mashtoo:
#        name: mashtoo