services:
    mashtoo:
        build:
            context: .
            args:
                ARCH: ${ARCH:-amd64}
                MICROARCH: ${MICROARCH:-}
                DIST: ${DIST:-debian}
                VERSION: ${VERSION:-latest}
                NETINST: ${NETINST:-0}
        container_name: mashtoo
        environment:
            - ARCH=${ARCH:-amd64}
            - MICROARCH=${MICROARCH:-}
            - DIST=${DIST:-debian}
            - VERSION=${VERSION:-latest}
            - NETINST=${NETINST:-0}
#            - SUFFIX=${SUFFIX}
#            - USB_DEVICE=${USB_DEVICE}
#        privileged: true
#        devices:
#            - /dev:/dev

networks:
    mashtoo:
        name: mashtoo