services:
    mashtoo:
        build:
            context: .
            args:
                ARCH: ${ARCH:-amd64}
                MICROARCH: ${MICROARCH:-}
                DIST: ${DIST:-debian}
                VERSION: ${VERSION:-latest}
                NETINST: ${NETINST:-0}
                SYSINIT: ${SYSINIT:-systemd}
                LOG_LEVEL: ${LOG_LEVEL:-ALL}
                USB_DEVICE: ${USB_DEVICE:-}
                DEBUG: ${DEBUG:-1}
        container_name: mashtoo
        environment:
            - ARCH=${ARCH:-amd64}
            - MICROARCH=${MICROARCH:-}
            - DIST=${DIST:-debian}
            - VERSION=${VERSION:-latest}
            - NETINST=${NETINST:-0}
            - SYSINIT=${SYSINIT:-systemd}
            - LOG_LEVEL=${LOG_LEVEL:-ALL}
            - USB_DEVICE=${USB_DEVICE:-}
            - DEBUG=${DEBUG:-1}
        privileged: true
        devices:
            - /dev:/dev
        volumes:
            - /dev:/dev
            - ./:/home/mashtoo

#networks:
#    mashtoo:
#        name: mashtoo
