#!/bin/sh
set -eu
exec > /dev/console 2>&1

set +u
if [ -f /lib/gentoo/functions.sh ]; then
    . /lib/gentoo/functions.sh
elif [ -f /sbin/functions.sh ]; then
    . /sbin/functions.sh
fi
set -u

chown -R ntp:ntp /run/chrony
chmod 755 /run/chrony

