#!/bin/sh
set -eu

help() {
    printf "Usage: %s <use_flag>\n" "${0}"
    printf "\n"
    printf "Display (if found) the description use_flag provided\n"
    exit 1
}

if [ "$#" -lt 1 ]; then
	help
fi

flag="${1}"
grep "^${flag} -" /var/db/repos/gentoo/profiles/use.desc
